#修改classpath
server:
  port: 8080
  servlet:
    context-path: /chen

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能
  datasource:
    username: root
    password: qazchenxijie
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 自定义数据源
    hikari:
      auto-commit: false
  servlet:
    multipart:  #文件大小限制
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    #username: 1345305701@qq.com
    #password: hnikomyarhtkicha
    #host: smtp.qq.com
    # qq需要配置ssl
    properties:
      mail:
        smtp:
          ssl:
            enable: true


#别名
mybatis:
  type-aliases-package: com.chen.pojo
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true

# 日志
#logging:
#  level:
#    com.chen.mapper: debug  # 包名根据自己的包名来

index:
  static:
    properties:
      myEmail: 1345305701@qq.com #我的邮箱
      everyPageTopicCount: 5 # 首页每页的topic数量
      topicRankCount: 10      # topic热度排行的数量
      topicNearCount: 10      # topic最新发布榜的数量
      hotUserCount: 5        # 热评用户榜的数量
      showFansCount: 10     #一页展示的fans数量
      showMessageCount: 5  #展示信息的数量
      avatar: /www/wwwroot/images/avatar/  # 头像路径
      topicPicture: /www/wwwroot/images/topicPicture/ #帖子封面路径
      otherPicture: /www/wwwroot/images/other/ #其他图片路径
      tagCount: 10
